apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-devops-dev
spec:
  selector:
    matchLabels:
      app: gke-devops-dev
  template:
    metadata:
      labels:
        app: gke-devops-dev
    spec:
      containers:
      - name: gke-devops-dev
        image: gcr.io/sunlit-charge-404811/gcpdevops-dev:latest
        resources: {}
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: gke-devops-dev
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: gke-devops-dev